import ical, { ICalCalendarMethod } from "ical-generator";
import { getVtimezoneComponent } from "@touch4it/ical-timezones";
import type { Config, StudySession } from "../types.js";

/**
 * Computes human-facing "Review 1" / "Review 2" numbering at render time by
 * sorting each source class's currently-scheduled sessions chronologically.
 * This number is never persisted — it's derived fresh on every render, per
 * spec ("Do not store reviewNumber as the source of truth").
 */
function computeReviewNumbers(sessions: StudySession[]): Map<string, number> {
  const bySource = new Map<string, StudySession[]>();
  for (const s of sessions) {
    if (!s.startUtc) continue;
    const list = bySource.get(s.sourceCanonicalId) ?? [];
    list.push(s);
    bySource.set(s.sourceCanonicalId, list);
  }

  const numbers = new Map<string, number>();
  for (const list of bySource.values()) {
    list.sort((a, b) => new Date(a.startUtc!).getTime() - new Date(b.startUtc!).getTime());
    list.forEach((s, idx) => numbers.set(s.id, idx + 1));
  }
  return numbers;
}

export interface IcsOutputOptions {
  domain: string;
  calendarName?: string;
}

/**
 * Builds a standards-compliant RFC 5545 ICS calendar containing only
 * currently SCHEDULED or (non-orphaned-irrelevant) LOCKED sessions with a
 * concrete placement. SKIPPED, CANCELLED, and NEEDS_ATTENTION sessions are
 * omitted, per spec.
 */
export function generateStudyIcs(
  sessions: StudySession[],
  config: Config,
  opts: IcsOutputOptions
): string {
  const visible = sessions.filter(
    (s) => (s.status === "SCHEDULED" || s.status === "LOCKED") && s.startUtc && s.endUtc
  );

  const reviewNumbers = computeReviewNumbers(visible);

  const cal = ical({
    name: opts.calendarName ?? "Study Sessions",
    timezone: { name: config.timezone, generator: getVtimezoneComponent },
    prodId: { company: "study-scheduler", product: "study-scheduler", language: "EN" },
    method: ICalCalendarMethod.PUBLISH,
  });

  for (const s of visible) {
    const reviewNumber = reviewNumbers.get(s.id) ?? 1;
    cal.createEvent({
      id: `${s.id}@${opts.domain}`,
      start: new Date(s.startUtc!),
      end: new Date(s.endUtc!),
      timezone: config.timezone,
      summary: `Review ${reviewNumber} — ${s.sourceSummary}`,
      description: buildDescription(s, reviewNumber),
      stamp: new Date(s.updatedAt),
    });
  }

  return cal.toString();
}

function buildDescription(s: StudySession, reviewNumber: number): string {
  const parts = [
    `Automatically scheduled study session (review ${reviewNumber}, "${s.reviewName}") for: ${s.sourceSummary}.`,
  ];
  if (s.status === "LOCKED") {
    parts.push(s.orphaned ? "Manually locked; the source class has since been removed from the timetable." : "Manually locked in place.");
  }
  parts.push("Generated by study-scheduler.");
  return parts.join(" ");
}
