import { createHash } from "node:crypto";

/**
 * ASSUMPTION (see README "genuinely unspecified assumptions"):
 *
 * Canonical source-event identity is derived from *content* — normalized
 * summary + exact start/end instants — rather than from the ICS UID.
 *
 * Rationale: university ICS exports are frequently regenerated by the
 * timetabling system with fresh UIDs even when nothing about the class
 * actually changed ("UID churn"). Since our identity key doesn't depend on
 * the UID at all, that kind of churn is a non-issue by construction: the
 * same class occurrence produces the same canonicalId run after run, so
 * its study sessions, locks, and history are preserved automatically.
 *
 * The raw UID is still recorded on the SourceEvent for diagnostics, and a
 * change in raw UID for an otherwise-identical occurrence is logged (see
 * normalize.ts) purely as an informational note, not as an identity signal.
 *
 * The trade-off: if a class's summary AND time both change in the same
 * feed regeneration, it is indistinguishable from "old class cancelled,
 * new class added" — which in practice is exactly how we want to treat a
 * class that moved to a materially different slot (its old non-locked
 * study sessions get cancelled; a fresh pair of reviews gets scheduled for
 * the new slot; a locked session survives as an orphan).
 */
export function computeCanonicalId(
  normalizedSummary: string,
  startUtcIso: string,
  endUtcIso: string
): string {
  const basis = `${normalizedSummary}|${startUtcIso}|${endUtcIso}`;
  return `se_${createHash("sha256").update(basis).digest("hex").slice(0, 24)}`;
}

export function normalizeSummary(summary: string): string {
  return summary.trim().toLowerCase().replace(/\s+/g, " ");
}
